# UI 접근용 NodePort (옵션)
# kubectl apply -f manifests/service/nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: namenode-ui
  namespace: hadoop
spec:
  type: NodePort
  selector:
    app: namenode
  ports:
    - name: http
      port: 9870
      nodePort: 30070
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager-ui
  namespace: hadoop
spec:
  type: NodePort
  selector:
    app: resourcemanager
  ports:
    - name: http
      port: 8088
      nodePort: 30088
---
apiVersion: v1
kind: Service
metadata:
  name: historyserver-ui
  namespace: hadoop
spec:
  type: NodePort
  selector:
    app: historyserver
  ports:
    - name: http
      port: 19888
      nodePort: 30188
