apiVersion: v1
kind: Service
metadata:
  name: namenode-svc
  namespace: hadoop
spec:
  selector:
    app: namenode
  ports:
    - name: rpc
      port: 8020
    - name: http
      port: 9870
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: datanode-svc
  namespace: hadoop
spec:
  clusterIP: None
  selector:
    app: datanode
  ports:
    - name: rpc
      port: 9864
    - name: http
      port: 9866
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager-svc
  namespace: hadoop
spec:
  selector:
    app: resourcemanager
  ports:
    - name: http
      port: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: historyserver-svc
  namespace: hadoop
spec:
  selector:
    app: historyserver
  ports:
    - name: http
      port: 19888
